In [1]:
import numpy as np
import pandas as pd

In [16]:
a = np.random.rand(5, 6)
d_arr = np.arange(1, 7)
d_mat = np.tile(d_arr, (5, 1))
print(a)
print(d_mat)

[[0.66467454 0.95801279 0.84449597 0.21081272 0.92359587 0.59065647]
 [0.0028505  0.40811518 0.64791677 0.71789936 0.11357025 0.36463148]
 [0.61695529 0.33241399 0.01921642 0.08892684 0.07656144 0.84373748]
 [0.07995716 0.51286217 0.06170719 0.28531114 0.25644993 0.45908959]
 [0.16259001 0.4459557  0.02779122 0.44303618 0.69506516 0.38667226]]
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [17]:
mask = a > 0.7
print(a * mask)

[[0.         0.95801279 0.84449597 0.         0.92359587 0.        ]
 [0.         0.         0.         0.71789936 0.         0.        ]
 [0.         0.         0.         0.         0.         0.84373748]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [18]:
idxs = np.where(mask.any(axis=1), mask.argmax(axis=1), -1)
print(idxs)

[ 1  3  5 -1 -1]


In [19]:
z_star = np.zeros((5, 6))
z_star[:, 0] = d_arr[idxs]
print(z_star)

[[2. 0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0. 0.]
 [6. 0. 0. 0. 0. 0.]
 [6. 0. 0. 0. 0. 0.]
 [6. 0. 0. 0. 0. 0.]]


In [74]:
x = np.split(b[1], np.unique(b[0], return_index=True)[1][1:])
print(x)

[array([0, 1, 4, 5], dtype=int64), array([0, 1, 2, 4], dtype=int64), array([0, 2, 3, 4, 5], dtype=int64), array([1, 3, 5], dtype=int64), array([1, 3, 4, 5], dtype=int64)]


In [62]:
x = np.array(x, dtype="object")

In [63]:
print(x)

[[0 1 4 5 0]
 [1 2 4 0 2]
 [3 4 5 1 3]
 [5 1 3 4 5]]


In [59]:
df

0
0     [0, 1, 4, 5]
1     [0, 1, 2, 4]
2  [0, 2, 3, 4, 5]
3        [1, 3, 5]
4     [1, 3, 4, 5]